version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: invoice-mysql-service
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: invoice-database
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
      MYSQL_USER: myuser
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge